-- Q4. Insert existing EMP values into NEWEMP when a record is updated.


SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER TR_EMPUPDATE
BEFORE UPDATE ON EMP
FOR EACH ROW
BEGIN
    INSERT INTO NEWEMP (EMPNO, ENAME, SAL)
    VALUES (:OLD.EMPNO, :OLD.ENAME, :OLD.SAL);
END;
/