-- Q5. Insert existing EMP values into NEWEMP when a record is deleted.


SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER TR_EMPDELETE
BEFORE DELETE ON EMP
FOR EACH ROW
BEGIN
    INSERT INTO NEWEMP (EMPNO, ENAME, SAL)
    VALUES (:OLD.EMPNO, :OLD.ENAME, :OLD.SAL);
END;
/