-- Q3. Insert values into NEWEMP when records are inserted into EMP

SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER TR_EMPINSERT
BEFORE INSERT ON EMP
FOR EACH ROW
BEGIN
    INSERT INTO NEWEMP (EMPNO, ENAME, SAL)
    VALUES (:NEW.EMPNO, :NEW.ENAME, :NEW.SAL);
END;
/
